### ISSUE TITLE
java.lang.NoClassDefFoundError: java/sql/SQLType

### ISSUE THREAD

**Issue by dannygu** [brettwooldridge/HikariCP#600]
Hi, 

We are currently running 2.4.2 on production and its working fine for us.

we started testing 2.4.4/2.4.5 and we are getting some strange errors which don't occur on 2.4.2.

Here is the error with 2.4.5, we are testing some very basic code with Groovy/Java.

java.lang.NoClassDefFoundError: java/sql/SQLType
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
        at java.lang.Class.getDeclaredMethods(Class.java:1860)
        at groovy.lang.MetaClass.addMethods(MetaClass.java:1159)
        at groovy.lang.MetaClass.<init>(MetaClass.java:139)
        at groovy.lang.MetaClassRegistry.getMetaClass(MetaClassRegistry.java:123)
        at org.codehaus.groovy.runtime.Invoker.invokeMethod(Invoker.java:144)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:104)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod(ScriptBytecodeAdapter.java:85)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeNoArgumentsMethod(ScriptBytecodeAdapter.java:154)
        at Script1.getAllRequestsCreatedBeforeWithActiveAI(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.groovy.runtime.ReflectionMetaMethod.invoke(ReflectionMetaMethod.java:67)
        at groovy.lang.MetaClass.doMethodInvoke(MetaClass.java:1386)
        at groovy.lang.MetaClass.invokeMethod(MetaClass.java:309)
        at org.codehaus.groovy.runtime.Invoker.invokeMethod(Invoker.java:165)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:104)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod(ScriptBytecodeAdapter.java:85)
        at Script1.run(Unknown Source)

in order to re-create this issue we wrote a very basic function you can find it here http://pastebin.com/KsAqbyQ0, we are unsure why this function runs fine with 2.4.2 and doesn't run with 2.4.4 or 2.4.5.

Thanks.

**Comment by mtambara** [comment]
We've been getting the same issue (`java.lang.NoClassDefFoundError: java/sql/SQLType`). It looks like this was introduced by 73491abb3184729d1ad1bb521432bd5538cdd54f. SQLType was introduced by Java 8 so we run into the `NoClassDefFoundError` when running our tests on Java 7. This was fine before version 2.4.4 because the `JavassistProxyFactory` used to ignore default methods when generating proxy classes, which were the only methods using `SQLType`. After this commit, classes were being generated containing `SQLType`. Since there is nothing in the [CHANGES](../blob/dev/CHANGES) indicating dropping support for Java 7, I'm guessing this is just a mistake? Reverting that commit fixes this on our end. 

cc @shuyangzhou

**Comment by brettwooldridge** [comment]
Ouch, this is going to be painful to fix.  It's weird that our automated tests on Java 7 don't encounter this error.  Can you provide your stack trace as well?  Is it during reflection activity of some sort?

**Comment by mtambara** [comment]
Yes, it's during reflection activity:
```
Caused by: java.lang.NoClassDefFoundError: java/sql/SQLType
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
	at java.lang.Class.privateGetPublicMethods(Class.java:2733)
	at java.lang.Class.getMethods(Class.java:1472)
	at com.liferay.portal.security.lang.DoPrivilegedHandler._initNotPrivilegedMethods(DoPrivilegedHandler.java:116)
	at com.liferay.portal.security.lang.DoPrivilegedHandler.<init>(DoPrivilegedHandler.java:44)
	at com.liferay.portal.security.lang.DoPrivilegedFactory$BeanPrivilegedAction.run(DoPrivilegedFactory.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.liferay.portal.security.lang.DoPrivilegedFactory.wrap(DoPrivilegedFactory.java:71)
	at com.liferay.portal.security.pacl.dao.jdbc.PACLConnectionHandler.invoke(PACLConnectionHandler.java:83)
	at com.sun.proxy.$Proxy600.prepareStatement(Unknown Source)
	at org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler.invoke(LazyConnectionDataSourceProxy.java:375)
	at com.sun.proxy.$Proxy13.prepareStatement(Unknown Source)
	at com.liferay.portal.security.pacl.test.SQLTest.executePreparedStatement(SQLTest.java:490)
	at com.liferay.portal.security.pacl.test.SQLTest.testDrop3(SQLTest.java:105)
Caused by: java.lang.ClassNotFoundException: java.sql.SQLType
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

**Comment by senior** [comment]
I hit this issue too. It seems like an easy way to resolve this issue would be to create a JDK 7 arifact separately from the JDK 8+ artifact. I tested this locally by setting JAVA_HOME to a JDK 7 directory before running maven install. My unit tests ran successfully after that (previously hit the above error).

**Comment by missedone** [comment]
here is similar issue at c3p0 https://github.com/swaldman/c3p0/issues/57, people suggested to compile the project with java7 (or -source -target flags.)

**Comment by alqershi** [comment]
The same issue happened with us as well. We had to revert back to an older version 2.4.1. I guess this issue will take sometime to be fixed.

**Comment by andysenn** [comment]
@brettwooldridge We just ran into this as well. Any rough guesses on when this will be resolved? We're stuck using Java 7 because we have to support our customers' environments. We're using the HikariCP-java7 artifact, so that fact that it doesn't actually support Java 7 is a bit misleading. Any update on the progress of this would be greatly appreciated!

**Comment by brettwooldridge** [comment]
@andysenn @alqershi @missedone @senior @mtambara @dannygu This is fixed in v2.4.11, just published to the Sonatype maven repository.

**Comment by andysenn** [comment]
@brettwooldridge You are my hero. :smile: Our integration tests are all passing again with the new version. Thank you for such a timely response!

**Comment by brettwooldridge** [comment]
@andysenn No problem, sorry for the inconvenience.  In the end the fix was simple.
