### ISSUE TITLE
NoClassDefFoundError after upgrading to 2.2.0

### ISSUE THREAD

**Issue by lespea** [brettwooldridge/HikariCP#172]
Just upgraded to `HikariCP 2.2.0` using sbt and when compiling I get these warnings:

```
[warn] Class com.codahale.metrics.MetricRegistry not found - continuing with a stub.
[warn] Class com.codahale.metrics.MetricRegistry not found - continuing with a stub.
[warn] Class com.codahale.metrics.MetricRegistry not found - continuing with a stub.
```

and when I try to create a connection pool I get this stack trace:

```
[info] Exception encountered when attempting to run a suite with class name: testing.schemas.generatedSchemas *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Lcom/codahale/metrics/MetricRegistry;
[info]   at java.lang.Class.getDeclaredFields0(Native Method)
[info]   at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
[info]   at java.lang.Class.getDeclaredFields(Class.java:1908)
[info]   at com.zaxxer.hikari.HikariConfig.copyState(HikariConfig.java:757)
[info]   at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:74)
---snip---
[info]   Cause: java.lang.ClassNotFoundException: com.codahale.metrics.MetricRegistry
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at java.lang.Class.getDeclaredFields0(Native Method)
[info]   at java.lang.Class.privateGetDeclaredFields(Class.java:2575)
[info]   at java.lang.Class.getDeclaredFields(Class.java:1908)
[info]   at com.zaxxer.hikari.HikariConfig.copyState(HikariConfig.java:757)
```

Running dependencyGraph these are the relevant lines if it's of any use:

```
[info]   +-com.zaxxer:HikariCP:2.2.0
[info]   | +-org.javassist:javassist:3.18.1-GA
[info]   | +-org.slf4j:slf4j-api:1.7.5 (evicted by: 1.7.7)
[info]   | +-org.slf4j:slf4j-api:1.7.7
```

Here is how I'm setting up the datasource; I've tried it with `failFast` to both `true` and `false`:

```
private[this] lazy val connPool = new HikariDataSource(new HikariConfig ~~ (
  _.setUsername(creds.username),
  _.setPassword(creds.pass),
  _.setReadOnly(readOnly),
  _.setDataSourceClassName(driverName),
  _.addDataSourceProperty("serverName", server),
  _.addDataSourceProperty("portNumber", port),
  _.addDataSourceProperty("databaseName", dbName),
  _.setPoolName(s"$server:$port-$dbName"),
  _.setInitializationFailFast(false),
  _.addDataSourceProperty("prepareSql", 3)))
```
