### ISSUE TITLE
NoClassDefFoundError after upgrading to 2.3.4

### ISSUE THREAD

**Issue by shawjef3** [brettwooldridge/HikariCP#286]
This is the same as issue [https://github.com/brettwooldridge/HikariCP/issues/172](172), except for version 2.3.4. The problem is fixed if I revert to 2.3.3.

**Comment by brettwooldridge** [comment]
I've published 2.3.5, it should be available in the next few hours.
