### ISSUE TITLE
module-info.class is missing from 6.3.1

### ISSUE THREAD

**Issue by billrobertson42** [brettwooldridge/HikariCP#2342]
Attempting to update from 6.2.1 to 6.3.1, and the (modular) project would no longer compile after updating the Hikari version to 6.3.1. Downgraded to 6.3.0 and all is well.

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/me/dev/demo-app/src/main/java/module-info.java:[15,24] module not found: com.zaxxer.hikari
``` 

```
$ javac --version
javac 23

$ java --version
openjdk 23 2024-09-17
OpenJDK Runtime Environment Corretto-23.0.0.36.1 (build 23+36-FR)
OpenJDK 64-Bit Server VM Corretto-23.0.0.36.1 (build 23+36-FR, mixed mode, sharing)
```

# pom fragments

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>

  <dependencyManagement>
            <dependency>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
                <version>6.3.1</version>
            </dependency>
  </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
    </dependencies>

        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.dagger</groupId>
                            <artifactId>dagger-compiler</artifactId>
                            <version>${dagger.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
```

6.3.0 is explicitly modularized, but 6.3.1 is not, and furthermore it has no Automatic-Module-Name either. Even if it had an Automatic-Module-Name, this would be a downgrade over the explicit module.

```
$ ismodularjar ~/.m2/repository/com/zaxxer/HikariCP/6.3.0/HikariCP-6.3.0.jar
y /c/Users/wrobert1/.m2/repository/com/zaxxer/HikariCP/6.3.0/HikariCP-6.3.0.jar module-info.class

$ ismodularjar ~/.m2/repository/com/zaxxer/HikariCP/6.3.1/HikariCP-6.3.1.jar
n /c/Users/wrobert1/.m2/repository/com/zaxxer/HikariCP/6.3.1/HikariCP-6.3.1.jar

$ cat `which ismodularjar`
#!/usr/bin/bash

unzip -l $1 | grep module-info.class > /dev/null
if [ $? -eq 0 ] ; then
    echo y $1 module-info.class
    exit 0
else
    m=`unzip -p $1 META-INF/MANIFEST.MF | grep Automatic-Module-Name`
    if [ $? -eq 0 ] ; then
        echo y $1 $m
        exit 0
    fi
fi
echo n $1
exit 1
```

More Confirmation

```
$ jar --describe-module --file=`cygpath -w ~/.m2/repository/com/zaxxer/HikariCP/6.3.0/HikariCP-6.3.0.jar`
com.zaxxer.hikari@6.3.0 jar:file:///C:/Users/me/.m2/repository/com/zaxxer/HikariCP/6.3.0/HikariCP-6.3.0.jar!/module-info.class
exports com.zaxxer.hikari
exports com.zaxxer.hikari.hibernate
exports com.zaxxer.hikari.metrics
exports com.zaxxer.hikari.metrics.dropwizard
exports com.zaxxer.hikari.metrics.micrometer
exports com.zaxxer.hikari.metrics.prometheus
exports com.zaxxer.hikari.pool
exports com.zaxxer.hikari.util
requires io.dropwizard.metrics5 static
requires java.base mandated
requires java.management
requires java.naming
requires java.sql
requires metrics.core static
requires metrics.healthchecks static
requires micrometer.core static
requires org.hibernate.orm.core static
requires org.javassist static
requires org.slf4j
requires simpleclient static


$ jar --describe-module --file=`cygpath -w ~/.m2/repository/com/zaxxer/HikariCP/6.3.1/HikariCP-6.3.1.jar`
No module descriptor found. Derived automatic module.

HikariCP@6.3.1 automatic
requires java.base mandated
contains com.zaxxer.hikari
contains com.zaxxer.hikari.hibernate
contains com.zaxxer.hikari.metrics
contains com.zaxxer.hikari.metrics.dropwizard
contains com.zaxxer.hikari.metrics.micrometer
contains com.zaxxer.hikari.metrics.prometheus
contains com.zaxxer.hikari.pool
contains com.zaxxer.hikari.util

```

**Comment by brettwooldridge** [comment]
@billrobertson42 v6.3.2 is publishing now and should be available within 30 minutes.
